---
version: "2.1"
services:
  nzbhydr2a2:
    image: lscr.io/linuxserver/nzbhydra2
    container_name: nzbhydr2a2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /config
      - /downloads
    ports:
      - 5076:5076
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined
